Hw05 parallel execution
grodrock/otus_go_class pull request #5
Opened 2022-01-05 13:50 UTC by grodrock

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-01-07 10:52 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако паралелльное выполнение заданий не реализовано. Следует учитывать, что задания могут выполняться существенно разное время.

Итого: 4 балла из 10
Возвращаю задачу на доработку

2022-01-07 10:52 UTC, agneum commented on hw05_parallel_execution/run.go
> +		for w := 0; w < n && i < len(tasks); w++ {
Такой саособ запуска не обеспечивает полностью конкурентной работы нескольких горутин. 
Проблема в запуске группами: если попадётся очень долгая задача, то, пока она не выполнится, другие задачи не будут запускаться.

Предлагаю передавать задачи в канал, из которого их будут конкурентно вычитывать и исполнять предварительно запущенные горутины

2022-01-07 10:52 UTC, agneum commented on hw05_parallel_execution/run.go
> +			}(tasks[i])
Более оптимальным будет вариант запуска `n` постоянных горутин вместо запуска горутины каждый раз для выполнения единственной задачи

2022-01-07 12:49 UTC, grodrock commented on hw05_parallel_execution/run.go
> +		for w := 0; w < n && i < len(tasks); w++ {
примерно так и делал сначала (пред. [коммит](https://github.com/grodrock/otus_go_class/pull/5/commits/b804f380b856e5595b16401ec59f64d7c17e5e99)), но не смог победить, тест не проходил т.к. не успевало выполнится тасков больше чем n+m

2022-01-08 10:45 UTC, agneum commented on hw05_parallel_execution/run.go
> +		for w := 0; w < n && i < len(tasks); w++ {
Это можно исправить, если проверять количество ошибок перед добавлением новой задачи на исполнение в канал.

В целом, первоначальная логика выглядит сложно - многовато каналов и струткур. Для решения задания достаточно одного канала для задач. Можно добавить ещё один для ошибок, если не хочется использовать мьютекс или атомик

2022-01-08 10:55 UTC, agneum approved these changes
Спасибо за правки. Отличная работа
Итого: 10 баллов из 10

2022-01-08 10:55 UTC, agneum commented on hw05_parallel_execution/run.go
> +			}
Можно заменить на `for-range`

2022-01-08 10:55 UTC, agneum commented on hw05_parallel_execution/run.go
> +		worker.Start(&wg, &errCounter)
Предложил бы вызов `Done()` и запуск горутины оставить здесь, в месте вызова - для лучшего контроля и наглядности

2022-01-08 13:26 UTC, merged